# Define the resource (the item to be created via API POST/PUT)
resource "scm_nat_rule" "dnat_external_web_test_create" {
  name        = "DNAT-External-data-src-test_1"
  description = "Translate public VIP to internal web server."

  # --- Required Traffic Selectors ---
  from        = ["zone-untrust"]
  to          = ["zone-untrust"]
  source      = ["any"]
  destination = ["any"]
  service     = "service-http"

  # --- Required Metadata ---
  folder   = "All"
  nat_type = "ipv4"
  position = "pre"

  # --- Destination Translation (DNAT) ---
  destination_translation = {
    translated_address = "10.1.1.16"
    translated_port    = 112
    dns_rewrite = {
      direction = "reverse"
    }
  }

}

# Define the data source (the item to be retrieved via API GET)
data "scm_nat_rule" "dnat_external_web_test_get" {
  # The data source needs the unique ID generated by the resource creation
  id = scm_nat_rule.dnat_external_web_test_create.id

}
# --- Output Blocks to Print Retrieved Data ---

output "retrieved_ID_and_name" {
  description = "The UUID and name of the retrieved NAT rule."
  value = {
    id   = data.scm_nat_rule.dnat_external_web_test_get.id
    name = data.scm_nat_rule.dnat_external_web_test_get.name
  }
}

output "retrieved_destination_translation" {
  description = "The full destination translation block, including the translated address."
  value       = data.scm_nat_rule.dnat_external_web_test_get.destination_translation
}

output "recieved_response" {
  description = "The full response object."
  value       = data.scm_nat_rule.dnat_external_web_test_get
}