package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// GetDataSources returns the list of data sources for this package.
func GetDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewIpsecTunnelDataSource,
		NewIkeCryptoProfileDataSource,
		NewBgpAddressFamilyProfileDataSource,
		NewLogicalRouterDataSource,
		NewBgpRouteMapDataSource,
		NewOspfAuthProfileDataSource,
		NewPbfRuleDataSource,
		NewZoneProtectionProfileDataSource,
		NewIpsecCryptoProfileDataSource,
		NewBgpFilteringProfileDataSource,
		NewSdwanPathQualityProfileDataSource,
		NewSdwanTrafficDistributionProfileDataSource,
		// 		NewAutoVpnClusterDataSource,
		NewLinkTagDataSource,
		NewAggregateEthernetInterfaceDataSource,
		NewRoutePathAccessListDataSource,
		NewQosProfileDataSource,
		NewBgpRedistributionProfileDataSource,
		NewSdwanErrorCorrectionProfileDataSource,
		NewRouteCommunityListDataSource,
		NewSdwanSaasQualityProfileDataSource,
		NewQosPolicyRuleDataSource,
		// 		NewSslDecryptionSettingDataSource,
		NewBgpRouteMapRedistributionDataSource,
		NewLayer2SubinterfaceDataSource,
		NewDnsProxyDataSource,
		NewIkeGatewayDataSource,
		NewRouteAccessListDataSource,
		NewVlanInterfaceDataSource,
		NewDhcpInterfaceDataSource,
		NewRoutePrefixListDataSource,
		NewInterfaceManagementProfileDataSource,
		NewBgpAuthProfileDataSource,
		NewLoopbackInterfaceDataSource,
		NewSdwanRuleDataSource,
		NewLayer3SubinterfaceDataSource,
		NewZoneDataSource,
		NewNatRuleDataSource,
		NewTunnelInterfaceDataSource,
		NewEthernetInterfaceDataSource,
		NewIpsecTunnelListDataSource,
		NewIkeCryptoProfileListDataSource,
		NewBgpAddressFamilyProfileListDataSource,
		NewLogicalRouterListDataSource,
		NewBgpRouteMapListDataSource,
		NewOspfAuthProfileListDataSource,
		NewPbfRuleListDataSource,
		NewZoneProtectionProfileListDataSource,
		NewIpsecCryptoProfileListDataSource,
		NewBgpFilteringProfileListDataSource,
		NewSdwanPathQualityProfileListDataSource,
		NewSdwanTrafficDistributionProfileListDataSource,
		// 		NewAutoVpnClusterListDataSource,
		NewLinkTagListDataSource,
		NewAggregateEthernetInterfaceListDataSource,
		NewRoutePathAccessListListDataSource,
		NewQosProfileListDataSource,
		NewBgpRedistributionProfileListDataSource,
		NewSdwanErrorCorrectionProfileListDataSource,
		NewRouteCommunityListListDataSource,
		NewSdwanSaasQualityProfileListDataSource,
		NewQosPolicyRuleListDataSource,
		// 		NewSslDecryptionSettingListDataSource,
		NewBgpRouteMapRedistributionListDataSource,
		NewLayer2SubinterfaceListDataSource,
		NewDnsProxyListDataSource,
		NewIkeGatewayListDataSource,
		NewRouteAccessListListDataSource,
		NewVlanInterfaceListDataSource,
		NewDhcpInterfaceListDataSource,
		NewRoutePrefixListListDataSource,
		NewInterfaceManagementProfileListDataSource,
		NewBgpAuthProfileListDataSource,
		NewLoopbackInterfaceListDataSource,
		NewSdwanRuleListDataSource,
		NewLayer3SubinterfaceListDataSource,
		NewZoneListDataSource,
		NewNatRuleListDataSource,
		NewTunnelInterfaceListDataSource,
		NewEthernetInterfaceListDataSource,
	}
}
