package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// GetDataSources returns the list of data sources for this package.
func GetDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewAggregateEthernetInterfaceDataSource,
		// 		NewAutoVpnClusterDataSource,
		NewBgpAddressFamilyProfileDataSource,
		NewBgpAuthProfileDataSource,
		NewBgpFilteringProfileDataSource,
		NewBgpRedistributionProfileDataSource,
		NewBgpRouteMapDataSource,
		NewBgpRouteMapRedistributionDataSource,
		NewDhcpInterfaceDataSource,
		NewDnsProxyDataSource,
		NewEthernetInterfaceDataSource,
		NewIkeCryptoProfileDataSource,
		NewIkeGatewayDataSource,
		NewInterfaceManagementProfileDataSource,
		NewIpsecCryptoProfileDataSource,
		NewIpsecTunnelDataSource,
		NewLayer2SubinterfaceDataSource,
		NewLayer3SubinterfaceDataSource,
		NewLinkTagDataSource,
		NewLogicalRouterDataSource,
		NewLoopbackInterfaceDataSource,
		NewNatRuleDataSource,
		NewOspfAuthProfileDataSource,
		NewPbfRuleDataSource,
		NewQosPolicyRuleDataSource,
		NewQosProfileDataSource,
		NewRouteAccessListDataSource,
		NewRouteCommunityListDataSource,
		NewRoutePathAccessListDataSource,
		NewRoutePrefixListDataSource,
		NewSdwanErrorCorrectionProfileDataSource,
		NewSdwanPathQualityProfileDataSource,
		NewSdwanRuleDataSource,
		NewSdwanSaasQualityProfileDataSource,
		NewSdwanTrafficDistributionProfileDataSource,
		// 		NewSslDecryptionSettingDataSource,
		NewTunnelInterfaceDataSource,
		NewVlanInterfaceDataSource,
		NewZoneDataSource,
		NewZoneProtectionProfileDataSource,
		NewAggregateEthernetInterfaceListDataSource,
		// 		NewAutoVpnClusterListDataSource,
		NewBgpAddressFamilyProfileListDataSource,
		NewBgpAuthProfileListDataSource,
		NewBgpFilteringProfileListDataSource,
		NewBgpRedistributionProfileListDataSource,
		NewBgpRouteMapListDataSource,
		NewBgpRouteMapRedistributionListDataSource,
		NewDhcpInterfaceListDataSource,
		NewDnsProxyListDataSource,
		NewEthernetInterfaceListDataSource,
		NewIkeCryptoProfileListDataSource,
		NewIkeGatewayListDataSource,
		NewInterfaceManagementProfileListDataSource,
		NewIpsecCryptoProfileListDataSource,
		NewIpsecTunnelListDataSource,
		NewLayer2SubinterfaceListDataSource,
		NewLayer3SubinterfaceListDataSource,
		NewLinkTagListDataSource,
		NewLogicalRouterListDataSource,
		NewLoopbackInterfaceListDataSource,
		NewNatRuleListDataSource,
		NewOspfAuthProfileListDataSource,
		NewPbfRuleListDataSource,
		NewQosPolicyRuleListDataSource,
		NewQosProfileListDataSource,
		NewRouteAccessListListDataSource,
		NewRouteCommunityListListDataSource,
		NewRoutePathAccessListListDataSource,
		NewRoutePrefixListListDataSource,
		NewSdwanErrorCorrectionProfileListDataSource,
		NewSdwanPathQualityProfileListDataSource,
		NewSdwanRuleListDataSource,
		NewSdwanSaasQualityProfileListDataSource,
		NewSdwanTrafficDistributionProfileListDataSource,
		// 		NewSslDecryptionSettingListDataSource,
		NewTunnelInterfaceListDataSource,
		NewVlanInterfaceListDataSource,
		NewZoneListDataSource,
		NewZoneProtectionProfileListDataSource,
	}
}
