package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// GetDataSources returns the list of data sources for this package.
func GetDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		// 		NewSslDecryptionSettingDataSource,
		NewSdwanSaasQualityProfileDataSource,
		NewQosPolicyRuleDataSource,
		// 		NewAutoVpnClusterDataSource,
		NewSdwanTrafficDistributionProfileDataSource,
		NewBgpFilteringProfileDataSource,
		NewRouteAccessListDataSource,
		NewIkeGatewayDataSource,
		NewPbfRuleDataSource,
		NewRoutePathAccessListDataSource,
		NewVlanInterfaceDataSource,
		NewRoutePrefixListDataSource,
		NewQosProfileDataSource,
		NewEthernetInterfaceDataSource,
		NewBgpRouteMapDataSource,
		NewIpsecTunnelDataSource,
		NewBgpRouteMapRedistributionDataSource,
		NewOspfAuthProfileDataSource,
		NewBgpAuthProfileDataSource,
		NewNatRuleDataSource,
		NewSdwanPathQualityProfileDataSource,
		NewBgpAddressFamilyProfileDataSource,
		NewLogicalRouterDataSource,
		NewLinkTagDataSource,
		NewIpsecCryptoProfileDataSource,
		NewInterfaceManagementProfileDataSource,
		NewAggregateEthernetInterfaceDataSource,
		NewLoopbackInterfaceDataSource,
		NewSdwanErrorCorrectionProfileDataSource,
		NewSdwanRuleDataSource,
		NewRouteCommunityListDataSource,
		NewTunnelInterfaceDataSource,
		NewLayer3SubinterfaceDataSource,
		NewZoneDataSource,
		NewBgpRedistributionProfileDataSource,
		NewDhcpInterfaceDataSource,
		NewIkeCryptoProfileDataSource,
		NewZoneProtectionProfileDataSource,
		NewLayer2SubinterfaceDataSource,
		NewDnsProxyDataSource,
		// 		NewSslDecryptionSettingListDataSource,
		NewSdwanSaasQualityProfileListDataSource,
		NewQosPolicyRuleListDataSource,
		// 		NewAutoVpnClusterListDataSource,
		NewSdwanTrafficDistributionProfileListDataSource,
		NewBgpFilteringProfileListDataSource,
		NewRouteAccessListListDataSource,
		NewIkeGatewayListDataSource,
		NewPbfRuleListDataSource,
		NewRoutePathAccessListListDataSource,
		NewVlanInterfaceListDataSource,
		NewRoutePrefixListListDataSource,
		NewQosProfileListDataSource,
		NewEthernetInterfaceListDataSource,
		NewBgpRouteMapListDataSource,
		NewIpsecTunnelListDataSource,
		NewBgpRouteMapRedistributionListDataSource,
		NewOspfAuthProfileListDataSource,
		NewBgpAuthProfileListDataSource,
		NewNatRuleListDataSource,
		NewSdwanPathQualityProfileListDataSource,
		NewBgpAddressFamilyProfileListDataSource,
		NewLogicalRouterListDataSource,
		NewLinkTagListDataSource,
		NewIpsecCryptoProfileListDataSource,
		NewInterfaceManagementProfileListDataSource,
		NewAggregateEthernetInterfaceListDataSource,
		NewLoopbackInterfaceListDataSource,
		NewSdwanErrorCorrectionProfileListDataSource,
		NewSdwanRuleListDataSource,
		NewRouteCommunityListListDataSource,
		NewTunnelInterfaceListDataSource,
		NewLayer3SubinterfaceListDataSource,
		NewZoneListDataSource,
		NewBgpRedistributionProfileListDataSource,
		NewDhcpInterfaceListDataSource,
		NewIkeCryptoProfileListDataSource,
		NewZoneProtectionProfileListDataSource,
		NewLayer2SubinterfaceListDataSource,
		NewDnsProxyListDataSource,
	}
}
