package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// GetResources returns all resources for the network_services package
func GetResources() []func() resource.Resource {
	return []func() resource.Resource{
		NewAggregateInterfaceResource,
		NewAutoVpnClusterResource,
		// 		NewAutoVpnPushResponseResource,
		NewAutoVpnSettingResource,
		NewBgpAddressFamilyProfileResource,
		NewBgpAuthProfileResource,
		NewBgpFilteringProfileResource,
		NewBgpRedistributionProfileResource,
		NewBgpRouteMapResource,
		NewBgpRouteMapRedistributionResource,
		NewConfigMatchListResource,
		NewDhcpInterfaceResource,
		NewDnsProxyResource,
		NewEthernetInterfaceResource,
		NewGlobalprotectMatchListResource,
		NewHipmatchMatchListResource,
		NewIkeCryptoProfileResource,
		NewIkeGatewayResource,
		NewInterfaceManagementProfileResource,
		NewIpsecCryptoProfileResource,
		NewIpsecTunnelResource,
		NewIptagMatchListResource,
		NewLayer2SubinterfaceResource,
		NewLayer3SubinterfaceResource,
		// 		NewLicenseResultResource,
		NewLinkTagResource,
		NewLldpProfileResource,
		NewLogicalRouterResource,
		NewLoopbackInterfaceResource,
		NewNatRuleResource,
		NewOspfAuthProfileResource,
		NewPbfRuleResource,
		NewQosPolicyRuleResource,
		NewQosProfileResource,
		NewRouteAccessListResource,
		NewRouteCommunityListResource,
		NewRoutePathAccessListResource,
		NewRoutePrefixListResource,
		NewSdwanErrorCorrectionProfileResource,
		NewSdwanPathQualityProfileResource,
		NewSdwanRuleResource,
		NewSdwanSaasQualityProfileResource,
		NewSdwanTrafficDistributionProfileResource,
		NewSystemMatchListResource,
		NewTunnelInterfaceResource,
		NewUseridMatchListResource,
		NewVlanInterfaceResource,
		NewZoneResource,
		NewZoneProtectionProfileResource,
	}
}
